services:
  db_pg_16:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PROD_DB_NAME:AdrianoCoffee}
      POSTGRES_USER: ${PROD_DB_USERNAME:postgres}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD:qduAanCahEqKZryOaghTouRSsVcRSPir}
    ports:
      - 5432
    container_name: postgres_con_3
    volumes:
      - C:\postgres_con_3:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: AdrianoCoffee-con
    ports:
      - 8080:8080
    depends_on:
      - db_pg_16
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_pg_16:5432/${PROD_DB_NAME:AdrianoCoffee}
      - SPRING_DATASOURCE_USERNAME=${PROD_DB_USERNAME:postgres}
      - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD:qduAanCahEqKZryOaghTouRSsVcRSPir}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop