spring.application.name=AdrianoCoffee

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

server.error.include-message=always
spring.docker.compose.enabled=false
spring.docker.compose.skip.in-tests=true

jwt.secret=${JWT_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=${java.io.tmpdir}

storage.type=cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

cors.allowed-origins=https://adriano-coffee.netlify.app/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mail.from.name=Adriano Coffee

stripe.publishable.key=${STRIPE_PB_KEY}
stripe.secret.key=${STRIPE_SC_KEY}
payment.provider=stripe

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.mandatory-file-encoding=UTF-8
server.address=0.0.0.0

# ??????? ???????? Stripe
stripe.timeout=8000

# HikariCP ? ????? ?????????? ??????
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.idle-timeout=300000