spring.application.name=AdrianoCoffee

spring.datasource.url=jdbc:postgresql://localhost:5432/AdrianoCoffee
spring.datasource.username=postgres
spring.datasource.password=Arspostgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

server.error.include-message=always
spring.docker.compose.enabled=false
spring.docker.compose.skip.in-tests=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778217A25432A

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

cors.allowed-origins=http://127.0.0.1:5500,http://127.0.0.1:5501